site_name: mlops-desafio-tecnico
repo_url: https://github.com/andressamarcal/mlops-desafio-tecnico
site_url: https://andressamarcal.github.io/mlops-desafio-tecnico
site_description: Projeto contendo as resoluções técnicas e teóricas
site_author: Andressa Marçal
edit_uri: edit/main/docs/
repo_name: andressamarcal/mlops-desafio-tecnico
copyright: Maintained by <a href="https://andressamarcal.com">Florian</a>.

nav:
  - Home: index.md
  - API: api.md
  - Código:
      - Models: models.md
      - Schemas: schemas.md
      - Data Service: data_service.md
      - Prediction Service: prediction_service.md
      - Main: main.md
      - Iris Router: iris_router.md
  - Modules: modules.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.insert(0, 'src')
          options:
            docstring_style: google

theme:
  name: material
  features:
    - tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/andressamarcal/mlops-desafio-tecnico
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mlops-desafio-tecnico

markdown_extensions:
  - toc
  - pymdownx.arithmatex
