site_name: Iris Classifier API Documentation
nav:
  - Home: index.md
  - Modules: modules.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
