site_name: mlops-desafio-tecnico
repo_url: https://github.com/andressamarcal/mlops-desafio-tecnico
site_url: https://andressamarcal.github.io/mlops-desafio-tecnico
site_description: Projeto contendo as resoluções técnicas e teóricas
site_author: Andressa Marçal
edit_uri: edit/main/docs/
repo_name: andressamarcal/mlops-desafio-tecnico
copyright: Maintained by <a href="https://andressamarcal.com">Florian</a>.

nav:
  - Home: index.md
  - API: api.md
  - Código:
      - Models: src/desafio1/api/common/models.py
      - Schemas: src/desafio1/api/common/schemas.py
      - Data Service: src/desafio1/api/services/data_service.py
      - Prediction Service: src/desafio1/api/services/prediction_service.py
      - Main: src/desafio1/api/v1/main.py
      - Iris Router: src/desafio1/api/v1/routers/iris_router.py
  - Modules: modules.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
          options:
            docstring_style: google

theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/andressamarcal/mlops-desafio-tecnico
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mlops-desafio-tecnico

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
