name: Main

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]

  push:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit flake8 black ruff mypy pytest pytest-cov

      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files

      - name: Run linter (flake8)
        run: |
          flake8 src tests

      - name: Run black
        run: |
          black --check src tests

      - name: Run ruff
        run: |
          ruff src tests

      - name: Run mypy
        run: |
          mypy src

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-fail-under=70

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocstrings

      - name: Check if documentation can be built
        run: mkdocs build -s
