name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          poetry-version: "1.8.1"

      - name: Install dependencies
        run: |
          poetry install

      - name: Run pre-commit checks
        run: |
          poetry run pre-commit run --all-files

      - name: Run linter
        run: |
          poetry run flake8 src tests

      - name: Run tests with coverage
        run: |
          poetry run pytest --cov=src --cov-fail-under=70

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          poetry-version: "1.8.1"

      - name: Install dependencies
        run: |
          poetry install

      - name: Check if documentation can be built
        run: poetry run mkdocs build -s
